// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5a0K3abajnUc1U2fKnGqa1EzKGvCkBJY',
    appId: '1:823935894482:web:60ba30b815f5875991be0b',
    messagingSenderId: '823935894482',
    projectId: 'projectmcsdht-d0951',
    authDomain: 'projectmcsdht-d0951.firebaseapp.com',
    storageBucket: 'projectmcsdht-d0951.firebasestorage.app',
    measurementId: 'G-4T998JF5DT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0s1hubse9BK5ltJ31byhmkKgE09qxy4Q',
    appId: '1:823935894482:android:a29df441ec474a6c91be0b',
    messagingSenderId: '823935894482',
    projectId: 'projectmcsdht-d0951',
    storageBucket: 'projectmcsdht-d0951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzbN8urTua6ZUOcZTtzGqZup5VtUbky2Y',
    appId: '1:823935894482:ios:cf315178cd3beffd91be0b',
    messagingSenderId: '823935894482',
    projectId: 'projectmcsdht-d0951',
    storageBucket: 'projectmcsdht-d0951.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzbN8urTua6ZUOcZTtzGqZup5VtUbky2Y',
    appId: '1:823935894482:ios:cf315178cd3beffd91be0b',
    messagingSenderId: '823935894482',
    projectId: 'projectmcsdht-d0951',
    storageBucket: 'projectmcsdht-d0951.firebasestorage.app',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5a0K3abajnUc1U2fKnGqa1EzKGvCkBJY',
    appId: '1:823935894482:web:4df2ee50459bd76a91be0b',
    messagingSenderId: '823935894482',
    projectId: 'projectmcsdht-d0951',
    authDomain: 'projectmcsdht-d0951.firebaseapp.com',
    storageBucket: 'projectmcsdht-d0951.firebasestorage.app',
    measurementId: 'G-QKE4XNNC4E',
  );
}
